"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, Plus, RefreshCw, Trash2 } from "lucide-react";

type Asset = Record<string, any>;

export function ReportWorkspace({ call, master, notify }: { call: (url: string, init?: RequestInit) => Promise<any>; master: { id: string; type: string; name: string }[]; notify: (text: string) => void }) {
  const [period, setPeriod] = useState("month"), [when, setWhen] = useState(new Date().toISOString().slice(0, 7)), [assets, setAssets] = useState<Asset[]>([]), [usage, setUsage] = useState<{ usedIds: string[] }>({ usedIds: [] }), [notes, setNotes] = useState<{ title: string; value: string }[]>([]);
  const owner = (id: string) => master.find(item => item.id === id)?.name || "Store";
  const load = async () => { try { const [data, used] = await Promise.all([call("/api/assets?page=1&size=10000"), call("/api/assets/usage")]); setAssets(data.items || []); setUsage(used || { usedIds: [] }); } catch (error: any) { notify(error.message); } };
  useEffect(() => { load(); }, []);
  const status = useMemo(() => ["UN_USED", "IN_USED", "BROKEN", "MAINTENANCE"].map(key => ({ key, value: assets.filter(asset => asset.status === key).length })), [assets]);
  const exportReport = () => { const lines = [["Kỳ báo cáo", period === "month" ? "Tháng" : "Quý", when], ["Tổng tài sản", "", String(assets.length)], ...status.map(item => [item.key, "", String(item.value)]), ["Đã qua sử dụng", "", String(usage.usedIds?.length || 0)], ...notes.map(item => [item.title, "", item.value])]; const csv = lines.map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `sub-asms-report-${when}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <section className="report-workspace panel"><div className="panel-head"><div><p className="portal-kicker">REPORT</p><h2>Báo cáo tài sản</h2><p className="muted">Admin có thể điều chỉnh dòng ghi chú trước khi xuất Excel.</p></div><div className="report-actions"><select value={period} onChange={event => setPeriod(event.target.value)}><option value="month">Theo tháng</option><option value="quarter">Theo quý</option></select><input type="month" value={when} onChange={event => setWhen(event.target.value)} /><button className="button secondary" onClick={load}><RefreshCw size={16} />Làm mới</button><button className="button" onClick={exportReport}><Download size={16} />Xuất Excel</button></div></div><div className="report-metrics"><div><span>Tổng tài sản</span><b>{assets.length}</b></div>{status.map(item => <div key={item.key}><span>{item.key}</span><b>{item.value}</b></div>)}<div><span>Đã qua sử dụng</span><b>{usage.usedIds?.length || 0}</b></div></div><section className="report-used"><h3>Danh sách Đã qua sử dụng</h3><div className="table-wrap"><table className="table"><thead><tr><th>Sub-Barcode</th><th>Owner</th><th>Status</th><th>Ticket</th></tr></thead><tbody>{assets.filter(asset => usage.usedIds?.includes(asset.id)).map(asset => <tr key={asset.id}><td>{asset.barcode}</td><td>{owner(asset.ownerId)}</td><td>{asset.status}</td><td>{asset.ticketId || "—"}</td></tr>)}</tbody></table>{!usage.usedIds?.length && <p className="empty">Chưa có tài sản thỏa điều kiện Đã qua sử dụng.</p>}</div></section><section className="report-notes"><div className="panel-head"><h3>Dòng điều chỉnh trước khi xuất</h3><button className="button secondary small" onClick={() => setNotes(items => [...items, { title: "Ghi chú", value: "" }])}><Plus size={14} />Thêm dòng</button></div>{notes.map((item, index) => <div className="report-note" key={index}><input value={item.title} onChange={event => setNotes(items => items.map((row, rowIndex) => rowIndex === index ? { ...row, title: event.target.value } : row))} /><input value={item.value} onChange={event => setNotes(items => items.map((row, rowIndex) => rowIndex === index ? { ...row, value: event.target.value } : row))} /><button className="icon-button" onClick={() => setNotes(items => items.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></div>)}</section></section>;
}
